@startuml
!include style.puml
skinparam ArrowFontStyle plain

actor User as User USER_COLOR

box UI UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
participant ":ListView" as ListView UI_COLOR
participant ":Popup" as Popup UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":CommandAutoCompleter" as AutoCompleter LOGIC_COLOR
end box

User -> CommandBox : types "add "
activate CommandBox UI_COLOR

CommandBox -> AutoCompleter : getSuggestions("add ")
activate AutoCompleter LOGIC_COLOR
AutoCompleter --> CommandBox : ["-student", "-tutorial"]
deactivate AutoCompleter

CommandBox -> ListView : setItems(suggestions)
activate ListView UI_COLOR
ListView --> CommandBox
deactivate ListView

CommandBox -> Popup : show(window, x, y)
activate Popup UI_COLOR
Popup --> User : display dropdown
deactivate Popup

deactivate CommandBox

User -> CommandBox : presses Tab
activate CommandBox UI_COLOR

CommandBox -> CommandBox : applySuggestion("-student")
activate CommandBox UI_COLOR
CommandBox --> CommandBox
deactivate CommandBox

CommandBox -> AutoCompleter : getSuggestions("add -student ")
activate AutoCompleter LOGIC_COLOR
AutoCompleter --> CommandBox : ["/name", "/phone", "/email", "/matric", "/tag"]
deactivate AutoCompleter

CommandBox -> ListView : setItems(suggestions)
activate ListView UI_COLOR
ListView --> CommandBox
deactivate ListView

CommandBox -> Popup : show(window, x, y)
activate Popup UI_COLOR
Popup --> User : display dropdown
deactivate Popup

deactivate CommandBox

@enduml
