@startuml
!include style.puml
skinparam ArrowFontStyle plain

actor User as User USER_COLOR

box UI UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
participant ":ListView" as ListView UI_COLOR
participant ":Popup" as Popup UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":CommandAutoCompleter" as AutoCompleter LOGIC_COLOR
end box

User -> CommandBox : types text
activate CommandBox

CommandBox -> AutoCompleter : getSuggestions(text)
activate AutoCompleter

ref over AutoCompleter
  Compute Suggestions
  For Command
  (sub-activity diagram)
end ref

AutoCompleter --> CommandBox : suggestions
deactivate AutoCompleter

CommandBox -> ListView : setItems(suggestions)
CommandBox -> Popup : show(window, x, y)

deactivate CommandBox

User -> CommandBox : presses Tab
activate CommandBox

CommandBox -> CommandBox : applySuggestion(suggestion)
activate CommandBox
deactivate CommandBox

deactivate CommandBox

@enduml
