@startuml
!include style.puml
skinparam ArrowFontStyle plain

package UI <<Rectangle>> UI_COLOR_T1 {
    class CommandBox UI_COLOR
}

package Logic <<Rectangle>> LOGIC_COLOR_T1 {
    class CommandAutoCompleter LOGIC_COLOR {
        +getSuggestions(text: String): List<String>
    }
}

show CommandAutoCompleter members

CommandBox "1" -right-> "1" CommandAutoCompleter : autoCompleter

@enduml
