@startuml
!include style.puml

start
:User types text in CommandBox;

if () then ([text empty])
    :List all command words;
else ([else])
    if () then ([no space in text])
        :Filter command words\nby typed prefix;
    else ([else])
        if () then ([first token is\na valid command word])
            :<<sub-activity>>\nCompute suggestions\nfor command;
        else ([else])
        endif
    endif
endif

stop

@enduml
