@startuml
!include style.puml

title Compute Suggestions For Command

start

if () then ([command is add])
    if () then ([no type flag yet])
        :Suggest type flags\n(-student / -tutorial);
    else ([else])
        if () then ([typing a "/" token])
            :Suggest matching unused\nprefixes for the flag type;
        else ([else])
        endif
    endif
else ([else])
    if () then ([command is delete or list])
        :Suggest type flags;
    else ([else])
        if () then ([command is find])
            :Suggest find flags;
        else ([else])
            if () then ([command is edit\nand typing a "/" token])
                :Suggest matching unused\nedit prefixes;
            else ([else])
            endif
        endif
    endif
endif

stop

@enduml
